DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS film_user_like CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS films
(
    film_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_id       integer,
    name         varchar(255) NOT NULL,
    description  varchar(200),
    release_date date         NOT NULL,
    duration     integer      NOT NULL,
    rate         numeric
        CONSTRAINT date_after CHECK (release_date > '1895-12-27'),
    CONSTRAINT film_duration_positive CHECK (duration > 0)
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   varchar(255)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  integer,
    genre_id integer,
    UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(255)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255) NOT NULL,
    login    varchar(255) NOT NULL,
    name     varchar(255),
    birthday date
        CONSTRAINT user_birthday_past_or_present CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS film_user_like
(
    user_id integer,
    film_id integer,
    UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_from integer NOT NULL,
    user_to   integer NOT NULL
);


ALTER TABLE films
    ADD FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id) ON DELETE CASCADE;

ALTER TABLE film_genre
    ADD FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE;

ALTER TABLE film_genre
    ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id) ON DELETE CASCADE;

ALTER TABLE film_user_like
    ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE film_user_like
    ADD FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE;

ALTER TABLE friends
    ADD FOREIGN KEY (user_from) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE friends
    ADD FOREIGN KEY (user_to) REFERENCES users (user_id) ON DELETE CASCADE;